# Generated by Django 5.1.1 on 2024-09-24 18:18

import emergency_contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0004_alter_contact_first_name_alter_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[emergency_contacts.models.validate_phone]),
        ),
    ]
